-- Script para agregar campos faltantes en Factura e ItemFactura en PostgreSQL
-- Ejecutar este script ANTES del despliegue

-- Campos faltantes en Factura
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "flete" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "seguro" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "tieneSeguro" BOOLEAN DEFAULT false;
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "codigoMincex" TEXT;
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "puertoEmbarque" TEXT DEFAULT 'NEW ORLEANS, LA';
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "origen" TEXT DEFAULT 'ESTADOS UNIDOS';
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "moneda" TEXT DEFAULT 'USD';
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "terminosPago" TEXT DEFAULT 'PAGO 100% ANTES DEL EMBARQUE';
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "incluyeFirmaCliente" BOOLEAN DEFAULT false;
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "firmaClienteNombre" TEXT;
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "firmaClienteCargo" TEXT;
ALTER TABLE "Factura" ADD COLUMN IF NOT EXISTS "firmaClienteEmpresa" TEXT;

-- Campos faltantes en ItemFactura
ALTER TABLE "ItemFactura" ADD COLUMN IF NOT EXISTS "cantidadSacos" DOUBLE PRECISION;
ALTER TABLE "ItemFactura" ADD COLUMN IF NOT EXISTS "pesoXSaco" DOUBLE PRECISION;
ALTER TABLE "ItemFactura" ADD COLUMN IF NOT EXISTS "precioXSaco" DOUBLE PRECISION;
ALTER TABLE "ItemFactura" ADD COLUMN IF NOT EXISTS "pesoXCaja" DOUBLE PRECISION;
ALTER TABLE "ItemFactura" ADD COLUMN IF NOT EXISTS "precioXCaja" DOUBLE PRECISION;
ALTER TABLE "ItemFactura" ADD COLUMN IF NOT EXISTS "codigoArancelario" TEXT;
